version: '3'

services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    tty: true
    volumes:
      - ./frontend:/usr/src/app/frontend
    command: sh -c "cd frontend  && yarn start"
    ports:
      - 3001:3000
  api:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    tty: true
    volumes:
      - ./api:/go/src/app
    command: sh -c "go run main.go"
    ports:
      - 8080:8080
  nginx:
    image: nginx
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node
      - api
